# Setup
title:               fermezz
tagline:             'rambles'
description:         'Things I write'
url:                 https://fermezz.com
baseurl:             ''
paginate:            5
permalink:           pretty
theme:               https://github.com/poole/lanyon

# About/contact
author:
  name:              Fernando Mez
  email:             fermez@gmail.com
  github:            https://github.com/fermezz
  twitter:           https://twitter.com/frozenamend

collections_dir: collections

collections:
  writings:
    output: true

excerpt_separator: <!--more-->

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.0.0
