# Setup
title:               fermezz
tagline:             'rambles'
description:         'Blog'
url:                 https://fermezz.com
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Fernando Mez
  email:             fermez@gmail.com
  github:            https://github.com/fermezz
  twitter:           https://twitter.com/frozenamend

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.0.0
